### Listar todas as empresas
GET http://localhost:8080/empresas

### Buscar empresa por ID
GET http://localhost:8080/empresas/1

### Criar uma nova empresa
POST http://localhost:8080/empresas
Content-Type: application/json

{
  "nome": "Tech Solutions LTDA",
  "cnpj": "55.666.777/0001-88",
  "emailContato": "contato@techsolutions.com"
}

### Atualizar a empresa de ID 1
PUT http://localhost:8080/empresas/1
Content-Type: application/json

{
  "nome": "Empresa Alfa Atualizada",
  "cnpj": "12.345.678/0001-90",
  "emailContato": "novoemail@empresa-alfa.com"
}

### Deletar a empresa de ID 2
DELETE http://localhost:8080/empresas/2