### Listar todas as vagas
GET http://localhost:8080/vagas

### Buscar vaga por ID
GET http://localhost:8080/vagas/1

### Criar uma nova vaga
POST http://localhost:8080/vagas
Content-Type: application/json

{
  "titulo": "Desenvolvedor Mobile",
  "descricao": "Desenvolvimento de apps em Flutter e Kotlin.",
  "publicacao": "2025-11-01",
  "ativo": true,
  "idEmpresa": 3
}

### Atualizar a vaga de ID 1
PUT http://localhost:8080/vagas/1
Content-Type: application/json

{
  "titulo": "Desenvolvedor Java Sênior",
  "descricao": "Atuação em projetos backend complexos com Spring Boot.",
  "publicacao": "2025-10-01",
  "ativo": true,
  "idEmpresa": 1
}

### Deletar a vaga de ID 2
DELETE http://localhost:8080/vagas/2